package io.github.tourem.maven.descriptor.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Represents a deployable module in a Maven project.
 * This includes JAR, WAR, EAR files and Spring Boot executables.
 * @author tourem

 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class DeployableModule {

    /**
     * Maven groupId
     */
    private String groupId;

    /**
     * Maven artifactId
     */
    private String artifactId;

    /**
     * Maven version
     */
    private String version;

    /**
     * Type of packaging (jar, war, ear)
     */
    private String packaging;

    /**
     * Path in Maven repository format
     * Example: com/larbotech/task/1.1.2-SNAPSHOT/task-1.1.2-SNAPSHOT.jar
     */
    private String repositoryPath;

    /**
     * Full URL to the artifact in the Maven repository (if repository URL is configured)
     * Example: https://nexus.example.com/repository/releases/com/larbotech/task/1.1.2-SNAPSHOT/task-1.1.2-SNAPSHOT.jar
     */
    private String repositoryUrl;

    /**
     * Final name of the artifact (may differ from artifactId-version if customized)
     */
    private String finalName;

    /**
     * Whether this is a Spring Boot executable
     */
    private boolean springBootExecutable;

    /**
     * Classifier if any (e.g., "exec", "sources", "javadoc")
     */
    private String classifier;

    /**
     * Relative path to the module from project root
     */
    private String modulePath;

    /**
     * Environment-specific configurations for each profile
     */
    private List<EnvironmentConfig> environments;

    /**
     * List of assembly artifacts generated by maven-assembly-plugin
     * Example: ZIP files with configuration for different environments
     */
    private List<AssemblyArtifact> assemblyArtifacts;

    /**
     * Java version required by the module (from maven.compiler.source or maven.compiler.release)
     */
    private String javaVersion;

    /**
     * Main class for Spring Boot applications
     */
    private String mainClass;

    /**
     * List of local module dependencies (other modules in the same project)
     */
    private List<String> localDependencies;

    /**
     * List of build plugins that indicate this module is potentially executable
     * Examples: spring-boot-maven-plugin, quarkus-maven-plugin, maven-shade-plugin,
     *           maven-assembly-plugin, jib-maven-plugin, dockerfile-maven-plugin
     */
    private List<String> buildPlugins;

    /**
     * Detailed executable information (type, method, structure, etc.)
     * This provides comprehensive information about how the module can be executed.
     */
    private ExecutableInfo executableInfo;

    /**
     * Container image information if a maintained container build plugin is configured
     * (Jib, Spring Boot build-image, Fabric8, Quarkus, Micronaut, ...).
     */
    private ContainerInfo container;
}

